// <auto-generated />
using System;
using FalconsRoost.Models.db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FalconsRoost.Models.DB.Migrations
{
    [DbContext(typeof(FalconsRoostDBContext))]
    [Migration("20250224025622_Alerts-CurrentlyRunning")]
    partial class AlertsCurrentlyRunning
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FalconsRoost.Models.Alerts.AlertMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AlertTarget")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("AlertTaskId")
                        .HasColumnType("char(36)");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AlertTaskId");

                    b.ToTable("AlertMessages");
                });

            modelBuilder.Entity("FalconsRoost.Models.Alerts.AlertTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AlertType")
                        .HasColumnType("int");

                    b.Property<bool>("CurrentlyRunning")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DayToRunOn")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("HourEndTime")
                        .HasColumnType("int");

                    b.Property<int>("HourStartTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastRun")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NextRun")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RecurrenceInterval")
                        .HasColumnType("int");

                    b.Property<int>("RecurrenceUnit")
                        .HasColumnType("int");

                    b.Property<bool>("RunOnStart")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RunOnce")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("AlertTasks");
                });

            modelBuilder.Entity("FalconsRoost.Models.ChatMessageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Channel")
                        .HasColumnType("longtext");

                    b.Property<string>("ChannelId")
                        .HasColumnType("longtext");

                    b.Property<string>("Guild")
                        .HasColumnType("longtext");

                    b.Property<string>("GuildId")
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ChatMessageLogs");
                });

            modelBuilder.Entity("FalconsRoost.Models.SimpleLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LaunchLogs");
                });

            modelBuilder.Entity("FalconsRoost.Models.Stats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("GoldOnHand")
                        .HasColumnType("int");

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("Wisdom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stats");

                    b.HasDiscriminator().HasValue("Stats");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FalconsRoost.Models.Weapon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionTextName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("BuyValue")
                        .HasColumnType("int");

                    b.Property<int>("DamageBonus")
                        .HasColumnType("int");

                    b.Property<int>("DiceSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumberOfDice")
                        .HasColumnType("int");

                    b.Property<Guid?>("OwnerId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<int>("SellValue")
                        .HasColumnType("int");

                    b.Property<Guid?>("StatsId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StatsId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("FalconsRoost.Models.Player", b =>
                {
                    b.HasBaseType("FalconsRoost.Models.Stats");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("LastMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LeagueOfComicGeeksName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Player");
                });

            modelBuilder.Entity("FalconsRoost.Models.Alerts.AlertMessage", b =>
                {
                    b.HasOne("FalconsRoost.Models.Alerts.AlertTask", null)
                        .WithMany("AlertMessages")
                        .HasForeignKey("AlertTaskId");
                });

            modelBuilder.Entity("FalconsRoost.Models.Weapon", b =>
                {
                    b.HasOne("FalconsRoost.Models.Stats", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FalconsRoost.Models.Stats", null)
                        .WithMany("Weapons")
                        .HasForeignKey("StatsId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FalconsRoost.Models.Alerts.AlertTask", b =>
                {
                    b.Navigation("AlertMessages");
                });

            modelBuilder.Entity("FalconsRoost.Models.Stats", b =>
                {
                    b.Navigation("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
